### ISSUE TITLE
add "REFERENCEABLE NODE LINKS" to the UI on admin/structure/types/manage/ page

### ISSUE THREAD

**Issue by knowledges33ker** [ElusiveMind/entity_reference_url#1]
![screen shot 2015-06-12 at 2 04 48 pm](https://cloud.githubusercontent.com/assets/1846944/8136729/23c8e638-110c-11e5-8066-81a795105c48.png)
The first two checkboxes in the screenshot above allow the user to specify whether a link should appear on the node teaser, the full node, both, or none. This is how the link to "add peer review" or "add related content" shows up.

The link title let's the user define what the link will be. So on a proposal, we would enter "add peer review" but on a session page we would change this to "add session review."

In our use case, the returned path is usually going to be the original node. This means the referenced node gets created and related to the original node but when that new node is saved the user is returned to the proposal/session or whatever node s/he was viewing.

Other options should include:
-the new node (this is the node that is created by clicking the link and is referenced to the original node)
-the referenced node (see comment above)
-the previous page (not sure exactly what this does, actually)

![screen shot 2015-06-12 at 2 08 10 pm](https://cloud.githubusercontent.com/assets/1846944/8136781/a2fce490-110c-11e5-834b-2fc14bce6b8d.png)

**Comment by ElusiveMind** [comment]
The inherent problem with this is that not all entities have teasers (only nodes I believe). So we will have to make that conditional on the type of entity being referenced.

**Comment by ElusiveMind** [comment]
A few observations. I have this working for nodes... however do we need to restrict entity references to types? Meaning that nodes can only reference nodes and taxonomy terms can only reference other terms? I have tried putting in an entity reference url for a taxonomy on a node and it pukes. I am thinking this is because they are two different entity types.

Can I get a use case for entity references on a taxonomy?

**Comment by knowledges33ker** [comment]
The most important functionality is for nodes. So if we have to roll it out with that functionality and a roadmap to include taxonomy at a later date that would be ok. 

One use case for taxonomy would be creating a hierarchical taxonomy where one term exists. The user is viewing that taxonomy term page and sees a link generated by this module to add related terms. 

This could be something like humanities which is an overarching category. I could go to the humanities taxonomy page and see a link to add related terms and make a new entity for English. Then another for art. Then another for history. Etc.

**Comment by ElusiveMind** [comment]
Fair enough. I suppose my question was that we're not going to try to cross support nodes with taxonomies ..... so you should only be able to reference the type of term you are working with and not -cross-reference them so to speak. Am I making sense? :)

**Comment by knowledges33ker** [comment]
Ah yes. That makes total sense. And yes agreed. Intra entity type referencing makes sense
