### ISSUE TITLE
reference to original not passed on node creation

### ISSUE THREAD

**Issue by knowledges33ker** [ElusiveMind/entity_reference_url#2]
When a new node is created by clicking the link generated by this module, the entityreference field should be pre-filled with the originating node id.

Currently, that value is not being passed:

![screen shot 2015-06-16 at 3 20 26 pm](https://cloud.githubusercontent.com/assets/1846944/8192352/777cb5fc-143b-11e5-8a0a-5c73732cde0a.png)

**Comment by ElusiveMind** [comment]
This issue should be addressed in the latest commit
