### ISSUE TITLE
URL generated by module is appearing in places where it shouldn't

### ISSUE THREAD

**Issue by knowledges33ker** [ElusiveMind/entity_reference_url#3]
See http://www.cwcon-sandbox.siteslab.org/ 

At the bottom of the page, there is a link to "add peer review." This link should only be visible if the content type is proposal.

In the settings for this field, the target type = node and the target bundle = proposal. So it should only show up on proposal pages, not on basic pages or other content types.

**Comment by ElusiveMind** [comment]
Actually. I think I know exactly why this is happening now.Coding up a fix

**Comment by ElusiveMind** [comment]
This should now be fixed. Please confirm
